// Auto-generated by webpack - do not edit manually
export const availableComponents = {
  "quarter-goals": {
    "name": "Quarterly Goals Generator",
    "icon": "🎯",
    "description": "generate quarterly goals for smart goal with AI assistance",
    "defaultPrompt": "Generate quarterly goals based on the provided smart goal.",
    "category": "productivity",
    "version": "1.0.0",
    "responseFormat": "json_schema",
    "recommendedModel": "gpt-4o",
    "recommendedTokens": 2500
  },
  "smart-goals": {
    "name": "Smart Goals Generator",
    "icon": "🎯",
    "description": "Create SMART goals with AI assistance",
    "defaultPrompt": "You are a SMART goals expert. Help users create Specific, Measurable, Achievable, Relevant, and Time-bound goals. Always provide structured, actionable goal statements with clear metrics and timelines.",
    "category": "productivity",
    "version": "1.0.0",
    "responseFormat": "json_object",
    "recommendedModel": "gpt-4",
    "recommendedTokens": 1000
  }
};

// Dynamic imports for component files
export const loadComponent = async (componentName) => {
    try {
        const component = await import(`./components/${componentName}/component.js`);
        return component.default;
    } catch (error) {
        console.error(`Failed to load component ${componentName}:`, error);
        return null;
    }
};
