// Auto-generated by webpack - do not edit manually
export const availableComponents = {
  "monthly-time-allocation": {
    "name": "Monthly Time Allocation",
    "icon": "📅",
    "description": "Plan and allocate time for routine tasks and goals across weeks",
    "category": "Planning",
    "version": "1.0.0",
    "dataSchema": {
      "selectedMonth": "string",
      "monthlyAllocation": "object"
    },
    "userMetaKeys": {
      "weekly_allocations": "monthly_time_allocation",
      "routine_tasks": "routine_tasks",
      "monthly_goals": "monthly_goals"
    },
    "defaultConfig": {
      "showRoutineTasks": true,
      "showMonthlyGoals": true
    }
  }
};

// Dynamic imports for component files
export const loadComponent = async (componentName) => {
    try {
        const component = await import(`./components/${componentName}/component.js`);
        return component.default;
    } catch (error) {
        console.error(`Failed to load component ${componentName}:`, error);
        return null;
    }
};
