// Auto-generated by webpack - do not edit manually
export const availableComponents = {
  "chronotype-test": {
    "name": "Chronotype Test",
    "icon": "🌅",
    "description": "Test component for chronotype assessment",
    "category": "Assessment",
    "version": "1.0.0",
    "dataSchema": {
      "testResults": "object"
    },
    "userMetaKeys": {
      "chronotype_results": "sv_cb_ct_results"
    },
    "defaultConfig": {
      "showResults": true
    }
  },
  "daily-task-picker": {
    "name": "Daily Task Picker",
    "icon": "📅",
    "description": "Pick and schedule daily tasks from weekly list with energy flow context",
    "category": "Planning",
    "version": "1.0.0",
    "dataSchema": {
      "selectedDate": "string",
      "chronotypeData": "object"
    },
    "userMetaKeys": {
      "monthly_allocation": "monthly_time_allocation",
      "chronotype_data": "sv_cb_udg_chronotype"
    },
    "defaultConfig": {
      "showEnergyFlow": true,
      "autoSaveEnabled": true,
      "autoSaveDelay": 1000
    },
    "features": [
      "Date picker with weekly context",
      "Energy flow visualization",
      "Weekly task pills (uncompleted todos only)",
      "Unplanned task creation",
      "Debounced auto-save",
      "AI trigger functionality",
      "Lithuanian language support"
    ],
    "dependencies": [
      "EditableTable component",
      "Monthly time allocation data",
      "Chronotype data for energy flow"
    ]
  },
  "monthly-time-allocation": {
    "name": "Monthly Time Allocation",
    "icon": "📅",
    "description": "Plan and allocate time for routine tasks and goals across weeks",
    "category": "Planning",
    "version": "1.0.0",
    "dataSchema": {
      "selectedMonth": "string",
      "monthlyAllocation": "object"
    },
    "userMetaKeys": {
      "weekly_allocations": "monthly_time_allocation",
      "routine_tasks": "routine_tasks",
      "monthly_goals": "monthly_goals"
    },
    "defaultConfig": {
      "showRoutineTasks": true,
      "showMonthlyGoals": true
    }
  },
  "weekly-todo-list": {
    "name": "Weekly Todo Breakdown",
    "icon": "✅",
    "description": "Break down weekly tasks into actionable todo items with add/remove functionality",
    "category": "Planning",
    "version": "1.0.0",
    "dataSchema": {
      "selectedWeek": "string",
      "weeklyTodos": "object"
    },
    "userMetaKeys": {
      "monthly_allocation": "monthly_time_allocation",
      "weekly_todos": "weekly_todo_breakdown"
    },
    "defaultConfig": {
      "allowAddTodos": true,
      "allowRemoveTodos": true,
      "showCompletedTodos": true,
      "autoSaveEnabled": false
    },
    "features": [
      "Week selector (previous/current/next week)",
      "Display tasks from monthly time allocation as group headers",
      "Add/remove actionable todo items under each task",
      "Save detailed breakdown with todo structure",
      "Integration with existing monthly allocation data"
    ],
    "dependencies": [
      "EditableTable component",
      "Monthly time allocation data"
    ]
  }
};

// Dynamic imports for component files
export const loadComponent = async (componentName) => {
    try {
        const component = await import(`./components/${componentName}/component.js`);
        return component.default;
    } catch (error) {
        console.error(`Failed to load component ${componentName}:`, error);
        return null;
    }
};
