<?php
/**
 * Server-side rendering for the Quarter Goals Generator block
 * Minimal render - just pass attributes to view.js
 *
 * @package sv-custom-blocks
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$wrapper_attributes = get_block_wrapper_attributes();

// Extract attributes with defaults
$display_options = array(
	'show_smart_goal' => isset( $attributes['sv_cb_qgoals_show_smart_goal'] ) ? $attributes['sv_cb_qgoals_show_smart_goal'] : true,
	'show_timeframe' => isset( $attributes['sv_cb_qgoals_show_timeframe'] ) ? $attributes['sv_cb_qgoals_show_timeframe'] : true,
	'show_assumptions' => isset( $attributes['sv_cb_qgoals_show_assumptions'] ) ? $attributes['sv_cb_qgoals_show_assumptions'] : false,
	'show_resources' => isset( $attributes['sv_cb_qgoals_show_resources'] ) ? $attributes['sv_cb_qgoals_show_resources'] : true,
	'show_risks' => isset( $attributes['sv_cb_qgoals_show_risks'] ) ? $attributes['sv_cb_qgoals_show_risks'] : false,
	'show_kpis' => isset( $attributes['sv_cb_qgoals_show_kpis'] ) ? $attributes['sv_cb_qgoals_show_kpis'] : true,
	'show_stages' => isset( $attributes['sv_cb_qgoals_show_stages'] ) ? $attributes['sv_cb_qgoals_show_stages'] : true,
	'show_actions' => isset( $attributes['sv_cb_qgoals_show_actions'] ) ? $attributes['sv_cb_qgoals_show_actions'] : true,
	'show_totals' => isset( $attributes['sv_cb_qgoals_show_totals'] ) ? $attributes['sv_cb_qgoals_show_totals'] : true,
);

$config_options = array(
	'assistant_id' => isset( $attributes['sv_cb_qgoals_assistant_id'] ) ? $attributes['sv_cb_qgoals_assistant_id'] : '',
	'allow_editing' => isset( $attributes['sv_cb_qgoals_allow_editing'] ) ? $attributes['sv_cb_qgoals_allow_editing'] : true,
	'group_actions_by_quarter' => isset( $attributes['sv_cb_qgoals_group_actions_by_quarter'] ) ? $attributes['sv_cb_qgoals_group_actions_by_quarter'] : true,
);

// Check if user is logged in
$is_logged_in = is_user_logged_in();

?>
<div <?php echo $wrapper_attributes; ?>>
	<div id="quarter-goals-generator" 
		 class="quarter-goals-container" 
		 data-display-options="<?php echo esc_attr( json_encode( $display_options ) ); ?>"
		 data-config-options="<?php echo esc_attr( json_encode( $config_options ) ); ?>"
		 data-is-logged-in="<?php echo esc_attr( $is_logged_in ? 'true' : 'false' ); ?>">
		<!-- All content will be generated by view.js -->
	</div>
</div>